#!/usr/bin/env bash
# first checks the arguments

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#the arguments to variables
path_to_file=$1
ip=$2
username=$3
path_ti_ssh_key=$4

#disabbling strict host key checking
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

#transfer check if trnsfer was successful
if [ $? -eq 0 ]
then
	echo "FILE TRANSFER WAS SUCCESSFUL"
else
	echo "FILE TRANSFER FAILED"
fi
