#!/usr/bin/env bash
# command to install nginx on web serve

#updating
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
